version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "hummingbot/core-dev"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "hummingbot/core-dev"
