[build-system]
requires = [
    "scikit-build-core>=0.5.0",
    "Cython>=0.29.33",
    "setuptools>=42.0.0",
    "wheel>=0.37.0",
    "cmake>=3.21.0"
]
build-backend = "scikit_build_core.build"

[project]
name = "hummingbot-candles-feed"
version = "0.1.0"
description = "A modular, plugin-based framework for fetching and managing candle data from cryptocurrency exchanges"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "Apache-2.0"}
authors = [
    {name = "Hummingbot Contributors", email = "dev@hummingbot.io"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Cython",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Financial :: Trading",
]
dependencies = [
    "pandas>=1.0.0",
    "numpy>=1.20.0",
    "aiohttp>=3.8.0",
    "websockets>=10.0",
    "pydantic>=1.8.0",
]

[project.urls]
Homepage = "https://github.com/MementoRC/hb-candles-feed"
Documentation = "https://github.com/MementoRC/hb-candles-feed/tree/main/docs"
Repository = "https://github.com/MementoRC/hb-candles-feed"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.11.0",
    "pytest-timeout>=2.1.0",
    "ruff>=0.1.5",
    "mypy>=1.5.1",
    "cython-lint>=0.15.0",
    "build>=1.0.3",
]
doc = [
    "mkdocs>=1.3.0",
    "mkdocs-material>=8.2.0",
    "mkdocstrings>=0.18.0",
]
hummingbot = [
    # Hummingbot-specific dependencies would go here
]

[tool.scikit-build]
# Enable wheel creation
wheel.packages = ["candles_feed"]
# Set source directory - only needed if CMakeLists.txt is not in the root
cmake.source-dir = "."
# Enable verbose CMake output for debugging
cmake.verbose = false
# Enable experimental features like parallel building
experimental = false
# Minimum version
minimum-version = "0.5.0"
# Handle macOS universal wheels
wheel.expand-macos-universal-tags = true
# Make sure sdist contains all necessary files
sdist.exclude = ["build", "dist", "_skbuild", "**/__pycache__", "**/*.pyc", ".git"]

[tool.ruff]
target-version = "py38"
line-length = 100

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "W",   # pycodestyle warnings
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
]
ignore = [
    "E203",  # whitespace before ':'
    "E501",  # line too long - handled by formatter
    "F401",  # unused imports - we'll address these gradually
]
unfixable = ["F401"]  # unused imports - let the developer decide

[tool.ruff.lint.isort]
known-first-party = ["candles_feed"]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
markers = [
    "unit: marks tests as unit tests",
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
    "e2e: marks tests as end-to-end tests",
    "asyncio: marks tests as asyncio tests",
]
log_cli = true
log_cli_level = "INFO"