name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ["MementoRC"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please verify these items before submitting
      options:
        - label: I have searched for existing issues that describe this bug
          required: true
        - label: I am using the latest version of hb-candles-feed
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the unexpected behavior...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Initialize adapter with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: exchange
    attributes:
      label: Exchange
      description: Which exchange adapter is affected?
      options:
        - Not exchange-specific
        - Binance (Spot)
        - Binance (Perpetual)
        - Coinbase Advanced Trade
        - Bybit (Spot)
        - Bybit (Perpetual)
        - Kraken (Spot)
        - Gate.io (Spot)
        - Gate.io (Perpetual)
        - OKX (Spot)
        - OKX (Perpetual)
        - Hyperliquid (Spot)
        - Hyperliquid (Perpetual)
        - KuCoin (Spot)
        - KuCoin (Perpetual)
        - MEXC (Spot)
        - MEXC (Perpetual)
        - AscendEX (Spot)
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Exchange Adapter
        - Core CandlesFeed
        - Data Processing
        - Network Client
        - Mock Server
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide your environment information
      value: |
        - hb-candles-feed version:
        - Python version:
        - Operating System:
        - Package manager (pixi/hatch/uv):
        - Hummingbot version (if applicable):
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Include relevant error messages, stack traces, or logs
      placeholder: Paste error logs here...
      render: text

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Minimal code example that reproduces the issue
      placeholder: |
        ```python
        from candles_feed import CandlesFeed
        
        # Minimal example that reproduces the bug
        ```
      render: python

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or relevant information
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: security
    attributes:
      label: Security Consideration
      description: Security-related checks
      options:
        - label: This bug does NOT involve security vulnerabilities (use private vulnerability reporting for security issues)
          required: true