name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: ["MementoRC"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please verify these items before submitting
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have checked the roadmap and planned features
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Exchange Adapter
        - Core Functionality Enhancement
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Testing/Quality
        - Security Enhancement
        - Integration/Compatibility
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the requested feature
      placeholder: Provide a concise summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the current limitation or problem:
        - What is currently difficult or impossible?
        - How does this impact users?
        - What use cases are not supported?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: |
        Describe how you envision this feature working:
        - What would the API look like?
        - How would users interact with it?
        - What would the behavior be?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches?
      placeholder: |
        Describe alternative approaches you've considered:
        - Other ways to solve the problem
        - Workarounds you've tried
        - Why the proposed solution is preferred

  - type: dropdown
    id: exchange
    attributes:
      label: Exchange-Specific Request
      description: Is this request specific to a particular exchange?
      options:
        - Not exchange-specific
        - Binance
        - Coinbase Advanced Trade
        - Bybit
        - Kraken
        - Gate.io
        - OKX
        - Hyperliquid
        - KuCoin
        - MEXC
        - AscendEX
        - New Exchange (specify in description)
        - Multiple Exchanges

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        ```python
        # Example usage of the proposed feature
        from candles_feed import CandlesFeed
        
        # Show how users would interact with the new feature
        ```
      render: python

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: Who would benefit from this feature?
      placeholder: |
        Describe the expected impact:
        - Who would use this feature?
        - How many users would benefit?
        - What's the expected usage frequency?
        - Are there any breaking changes?

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Technical considerations (check all that apply)
      options:
        - label: This feature requires new dependencies
        - label: This feature may have performance implications
        - label: This feature requires documentation updates
        - label: This feature requires new tests
        - label: This feature may affect existing APIs
        - label: This feature requires security review

  - type: textarea
    id: technical
    attributes:
      label: Technical Details
      description: Any technical considerations or implementation ideas
      placeholder: |
        Share any technical thoughts:
        - Implementation approach ideas
        - Potential challenges
        - Performance considerations
        - Compatibility requirements

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        Provide additional context:
        - Related issues or PRs
        - External resources or references
        - Timeline requirements
        - Business justification

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Are you interested in contributing to this feature?
      options:
        - label: I would be interested in contributing to this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature