name: Package CI

on:
  push:
    branches: [main, master, develop, development]
  pull_request:
    branches: [main, master, develop, development]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          auto-activate-base: true
      
      - name: Install dependencies
        run: |
          conda install -c conda-forge hatch
          hatch env create

      - name: Run tests
        run: |
          hatch run test

      - name: Run coverage
        run: |
          hatch run test --cov=candles-feed

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          auto-activate-base: true

      - name: Install dependencies
        run: |
          conda install -c conda-forge hatch
          hatch env create
      
      - name: Build package
        run: |
          python -m build
      
      - name: Store built packages
        uses: actions/upload-artifact@v4
        with:
          name: dist-py${{ matrix.python-version }}
          path: dist/

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          auto-update-conda: true
          auto-activate-base: true
      
      - name: Install dependencies
        run: |
          conda install -c conda-forge hatch
          hatch env create
      
      - name: Format and lint with ruff
        run: |
          ruff format --check .
          ruff check .
      
      - name: Type check with mypy
        run: |
          mypy --install-types --non-interactive --ignore-missing-imports candles_feed/
